import pyautogui
import time

pyautogui.moveTo(150, 1052) 
pyautogui.click()
time.sleep(1.5)
pyautogui.write("https://drive.google.com/drive", interval=0.1)
pyautogui.press('enter')
pyautogui.moveTo(200,490)
time.sleep(1.5)
# pyautogui.click()
#time.sleep(3.7)
#pyautogui.moveTo(1150,525)
#pyautogui.click()
#time.sleep(2)
pyautogui.moveTo(95, 205)
time.sleep(3)
pyautogui.click()
time.sleep(2)
pyautogui.moveTo(95,390)
pyautogui.click()
pyautogui.moveTo(450,400)
time.sleep(4)
pyautogui.click()
pyautogui.write("PYAUTOGUI", interval=0.1)
pyautogui.moveTo(450,500)
time.sleep(2)
pyautogui.click()
pyautogui.write("autoclicker", interval=0.1)
pyautogui.moveTo(1150,525)
pyautogui.click()
time.sleep(3)
pyautogui.moveTo(515,15)
pyautogui.click()
time.sleep(1)
pyautogui.moveTo(425,740)
pyautogui.click()
pyautogui.hotkey('ctrl','a')
pyautogui.hotkey('ctrl','c')
pyautogui.click()
time.sleep(2)
pyautogui.moveTo(80,180)
pyautogui.click()
time.sleep(2)
pyautogui.moveTo(500,500)
pyautogui.click()
pyautogui.hotkey('ctrl','v')
pyautogui.write("<3 ", interval=0.1)
